create table tag_names (
  name text primary key
);
grant all on tag_names to spotify_metadata;

create table tags (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text references tag_names(name),
  value text
);
grant all on tags to spotify_metadata;

create table tracks (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  url text
);
grant all on tracks to spotify_metadata;

create table tracks_tags (
  track_id int not null references tracks(id),
  tag_id   int not null references tags(id),
  primary key (track_id, tag_id)
);
grant all on tracks_tags to spotify_metadata;

insert into tag_names(name) values
  ('Composer'),
  ('Conductor');

insert into tracks (name, url) values
  ('Kuuus, Kuus Kallike', 'https://open.spotify.com/track/4lKxFmCzfylBvUMcevipgB'),
  ('Lullabie', 'https://open.spotify.com/track/4enVGptNu9f8SsNkHDRgWH'),
  ('With dropping wings ye Cupids come','https://open.spotify.com/track/0iMwiy7v5VNssHCRpZlsf7');

insert into tags (name, value) values
  ('Composer', 'Arvo Pärt'),
  ('Composer', 'Anthony Holborne'),
  ('Conductor', 'Jordi Savall ');

insert into tracks_tags (track_id, tag_id) values
  (1, 1),
  (1, 3),
  (2, 2),
  (2, 3);
