-- List of all valid tag names
create table tag_names (
  name text not null primary key
);
grant all on tag_names to spotify_metadata;

-- A single table for all tags applied to albums, tracks and anything else I think of
create table tags (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text not null references tag_names(name),
  value text not null
);
grant all on tags to spotify_metadata;

-- A table of tracks, usually associated with an album. They are identified with the spotify id. No spotify data
-- is cached but this might change to reduce the number of calls we make to spotify.
create table tracks (
  id text not null PRIMARY KEY
);
grant all on tracks to spotify_metadata;

-- Tags applied to a track. Its a many to many relationship so we need this intermediate table
create table tracks_tags (
  track_id text not null references tracks(id),
  tag_id   int not null references tags(id),
  primary key (track_id, tag_id)
);
grant all on tracks_tags to spotify_metadata;

-- Table of album identified by the spotify id. As with tracks we don't cache any spotify data at the moment.
create table albums (
  id text not null PRIMARY KEY
);

-- Tags applied to an album. Its a many to many relationship so we need this intermediate table
create table album_tags (
  album_id text not null references albums(id),
  tag_id   int not null references tags(id),
  primary key (album_id, tag_id)
);
grant all on album_tags to spotify_metadata;
