export const conductors = [
    // 'Aaron Copland',
    // 'Abe Lyman',
    // 'Ace Brigode',
    // 'Ádám Fischer',
    // 'Adam Gatehouse',
    // 'Adam Kopyciński',
    // 'Adolf Čech',
    // 'Adolph Deutsch',
    // 'Adrian Adlam',
    // 'Adrian BOULT',
    // 'Adrian Shepherd',
    // 'Afrasiyab Badalbeyli',
    // 'Agide Jacchia',
    // 'Ahn Eak-tai',
    // 'Åke Uddén',
    // 'Akeo Watanabe',
    // 'Al Goodman',
    // 'Al Tabor',
    // 'Alan Hazeldine',
    // 'Alan Holley',
    // 'Albert F. Schoepper',
    // 'Albert Ferber',
    // 'Albert Pratz',
    // 'Albert Rosen',
    // 'Albert Stoessel',
    // 'Albert Tipton',
    // 'Albert van Raalte',
    'Alberto Lizzio',
    'Alberto Williams',
    'Aleksander Szeligowski',
    'Aleksandr Gauk',
    'Aleksandr Yurasovsky',
    'Aleksandre Machavariani',
    'Alex Hyde',
    'Alex Prior',
    'Alex Stobbs',
    'Alexander Chuhaldin',
    'Alexander Faris',
    'Alexander Glazunov',
    'Alexander Koshetz',
    'Alexander Olshanetsky',
    'Alexander Shelley',
    'Alexander Vakoulsky',
    'Alexander Vladimirovich Varlamov',
    'Alexei Gorokhov',
    'Alfred James Phasey',
    'Alfred Nash Patterson',
    'Alfred Strombergs',
    'Alfred Uhl',
    'Alfred Wallenstein',
    'Alfredo Antonini',
    'Alfrēds Kalniņš',
    'Allan McIver',
    'Alma Rosé',
    'Aloys Fleischmann',
    'Alun Francis',
    'Anatole Fistoulari',
    'Anatoly Lyadov',
    'Anatoly Novikov',
    'Andre Kostelanetz',
    'André Previn',
    'André Rieu',
    'Andres Mustonen',
    'Andrew Carwood',
    'Andrew Constantine',
    'Andrew Gourlay',
    'Andrew Lawrence-King',
    'Andrew Manze',
    'Andrew Millington',
    'Andrew Mogrelia',
    'Andrew Parrott',
    'Andrew-John Smith',
    'Andrzej Markowski',
    'Andrzej Panufnik',
    'Angela Gehann-Dernbach',
    'Angelo Ephrikian',
    'Aníbal Troilo',
    'Anne Manson',
    'Anson Weeks',
    'Antal Doráti',
    'Anthony Bernard',
    'Anthony Korf',
    'Anthony Marinelli',
    'Antiochos Evangelatos',
    'Anton Hartman',
    'Anton Nanut',
    'Antonia Brico',
    'Antonino Votto',
    'António Fortunato de Figueiredo',
    'Antonio Janigro',
    'Antonio Morelli',
    'Antonio PAPPANO',
    'Antonio Pedrotti',
    'Antony Hopkins',
    'Apo Hsu',
    'Argeo Quadri',
    'Aristotelis Koundouroff',
    'Arnold Safroni-Middleton',
    'Arpad Darazs',
    'Artemi Ayvazyan',
    'Arthur Dennington',
    'Arthur Duff',
    'Arthur Fiedler',
    'Arthur Greenslade',
    'Arthur Mendel',
    'Arthur Nikisch',
    'Arthur Oldham',
    'Artur Rodziński',
    'Arturo TOSCANINI',
    'Arturo Vigna',
    'Arvid Franzen',
    'Arvīds Jansons',
    'Arwel Hughes',
    'Ashley William Joseph',
    'Ataúlfo Argenta',
    'August Wenzinger',
    'Augustin Dumay',
    'Austin Wylie',
    'Avril Coleridge-Taylor',
    'Aylmer Buesst',
    'Barbara Hannigan',
    'Barry Gray',
    'Barry Wordsworth',
    'Ben Berlin',
    'Ben McPeek',
    'Ben Selvin',
    'Benjamin Bayl',
    'Benjamin BRITTEN',
    'Benny de Weille',
    'Berislav Šipuš',
    'Bernard HAITINK',
    'Bernard Heinze',
    'Bernhard Klee',
    'Bernhard Sieberer',
    'Bertrand de Billy',
    'Bill Conti',
    'Bill McGlaughlin',
    'Billy Cotton',
    'Billy Ternent',
    'Blaoui Houari',
    'Bob Chilcott',
    'Bohdan Warchal',
    'Boris Papandopulo',
    'Boyd Neel',
    'Bram Gay',
    'Bratislav Anastasijević',
    'Brent Crayon',
    'Břetislav Bakala',
    'Brian Boydell',
    'Brian Brockless',
    'Brian Israel',
    'Brian Newbould',
    'Bruno Maderna',
    'Bruno WALTER',
    'Bryan Fairfax',
    'Bryden Thomson',
    'Byron Fidetzis',
    'Calvin E. Simmons',
    'Camil Van Hulse',
    'Caravelli',
    'Carl Crossin',
    'Carl Gustav Sparre Olsen',
    'Carl Kiefert',
    'Carl Nielsen',
    'Carl Reinecke',
    'Carl Schuricht',
    'Carl St. Clair',
    'Carl von Garaguly',
    'Carlo Giorgio Garofalo',
    'Carlo Maria GIULINI',
    'Carlo Taube',
    'Carlo Zecchi',
    'Carlos Chávez',
    'Carlos Kalmar',
    'Carlos KLEIBER',
    'Carlos Païta',
    'Carlton Jones Lake',
    'Carolyn Kuan',
    'Catherine Rückwardt',
    'Cedric Thorpe Davie',
    'César Guerra-Peixe',
    'Charles E. King',
    'Charles Hazlewood',
    'Charles MACKERRAS',
    'Charley Straight',
    'Charlie Creath',
    'Charlie Kunz',
    'Christiaan Kriens',
    'Christian Thielemann',
    'Christina Pluhar',
    'Christoph Eschenbach',
    'Christopher Austin',
    'Christopher D. Cook',
    'Christopher Finzi',
    'Christopher HOGWOOD',
    'Christopher Keene',
    'Christopher Moulds',
    'Christopher Seaman',
    'Ciril Cvetko',
    'Clara Novello Davies',
    'Claude T. Smith',
    'Claudio Abbado',
    'Claus Ogerman',
    'Clemens Krauss',
    'Clement Power',
    'Colin Brumby',
    'Colin DAVIS',
    'Constant Lambert',
    'Constantin Bakaleinikoff',
    'Constantin Silvestri',
    'Courtney Lewis',
    'Crawford Gates',
    'Cyril Ornadel',
    'Dafnis Prieto',
    'Dafydd Llywelyn',
    'Damien Top',
    'Damon Gupton',
    'Dan Welcher',
    'Daniel BARENBOIM',
    'Daniel Harding',
    'Daniel Protheroe',
    'Daniel Sternberg',
    'Daniel Sternefeld',
    'Daniele Amfitheatrof',
    'Daniele Rustioni',
    'Danilo Švara',
    'Dan-Olof Stenlund',
    'David Avshalomov',
    'David Firman',
    'David Hattner',
    'David Josefowitz',
    'David Martyn Jones',
    'David Measham',
    'David Munrow',
    'David Robert Coleman',
    'David Russell Hulme',
    'David Temple',
    'David Trendell',
    'David Willcocks',
    'David Zinman',
    'Dean Dixon',
    'Dennis Russell Davies',
    'Derek Bourgeois',
    'Dick Jacobs',
    'Dick Manning',
    'Diethard Hellmann',
    'Dilbar Abdurahmonova',
    'Dimiter Manolov',
    'Dimitri Mitropoulos',
    'Dimitri Tiomkin',
    'Dmitri Jurowski',
    'Dobrin Petkov',
    'Doc Cook',
    'Dolf van der Linden',
    'Domingo Hindoyan',
    'Don Azpiazú',
    'Donald Runnicles',
    'Donny Hathaway',
    'Douglas Bostock',
    'Douglas Boyd',
    'Douglas Guest',
    'Duke Ellington',
    'Earl Burtnett',
    'Earl Wild',
    'Ed Kirkeby',
    'Edgar Doneux',
    'Edo de Waart',
    'Édouard Woolley',
    'Eduard Flipse',
    'Eduard Oja',
    'Eduard Strauss II',
    'Eduard Toldrà',
    'Eduard van Beinum',
    'Eduardo Alonso-Crespo',
    'Eduardo Diazmuñoz',
    'Eduardo Mata',
    'Edward Elgar',
    'Edward Elwyn Jones',
    'Edward German',
    'Edward Vesala',
    'Edwin McArthur',
    'Efrem Zimbalist',
    'Egon Hilbert',
    'Egon Kornauth',
    'Elias Breeskin',
    'Eliseo Grenet',
    'Emanuel Balaban',
    'Emanuel Leplin',
    'Emerson Buckley',
    'Emil Młynarski',
    'Emil Reesen',
    'Emil Simon',
    'Émile Stern',
    'Emma Roberto Steiner',
    'Ennio Morricone',
    'Enrico Lopez-Yañez',
    'Enrico Mainardi',
    'Enrico Simonetti',
    'Erhard Mauersberger',
    'Eric Fogg',
    'Eric Gilder',
    'Eric Robinson (conductor)',
    'Erich Bergel',
    'Erich Kleiber',
    'Erich Kunzel',
    'Erich Leinsdorf',
    'Ernest Ansermet',
    'Ernest Llewellyn',
    'Ernest MacMillan',
    'Ernö Rapée',
    'Ernst Bachrich',
    'Ernst Levy',
    'Erol Erdinç',
    'Erskine Tate',
    'Esa-Pekka Salonen',
    'Ettore Mazzoleni',
    'Eugen Jochum',
    'Eugen Pricope',
    'Eugene Aynsley Goossens',
    'Eugène Chartier',
    'Eugene ORMANDY',
    'Eugène Ysaÿe',
    'Eva Ollikainen',
    'Evald Aav',
    'Evan Stephens',
    'Everett Lee',
    'Ezra Rachlin',
    'Fabien Sevitzky',
    'Fărâmiță Lambru',
    'Fate Marable',
    'Fausto Cleva',
    'Feargus Hetherington',
    'Fedor Glushchenko',
    'Felix Bernard',
    'Felix Krohn',
    'Felix Mills',
    'Felix Slatkin',
    'Ferdinand Löwe',
    'Ferenc Farkas',
    'Ferenc Fricsay',
    'Fernand Oubradous',
    'Fernando Lopes-Graça',
    'Fernando Rosas Pfingsthorn',
    'Ferruccio Busoni',
    'Ferrucio Calusio',
    'Filmer Hubble',
    'Fletcher Henderson',
    'Frances Williams',
    'Francesco Cilluffo',
    'Francesco d\'Avalos',
    'Francesco Libetta',
    'Franck Pourcel',
    'Franco Capuana',
    'Franco Vittadini',
    'François Weigel',
    'Françoys Bernier',
    'Frank Bridge',
    'Frank Cordell',
    'Frank Renton',
    'Frank St. Leger',
    'Frank Van der Stucken',
    'František Brož',
    'František Jílek',
    'Franz Allers',
    'Franz Salmhofer',
    'Franz Wasner',
    'Fred Rich',
    'Frederic Curzon',
    'Frederick Albert Bridge',
    'Frederick Haggis',
    'Frederico de Freitas',
    'Frédérique Petrides',
    'Frieda Belinfante',
    'Friedrich Baumfelder',
    'Friedrich Kark',
    'Fritz Brun',
    'Fritz Busch',
    'Fritz Lehmann',
    'Fritz Mahler',
    'Fritz Münch',
    'Fritz REINER',
    'Fritz Werner',
    'Gabriel Migliori',
    'Gaetano Bavagnoli',
    'Garry Walker',
    'Gaston Poulet',
    'Gavin Henderson',
    'Gene Kardos',
    'Gene Rodemich',
    'Gennady Dmitryak',
    'Gennady Rozhdestvensky',
    'Geoffrey Paterson',
    'Georg SOLTI',
    'Georg Tintner',
    'George Andreani',
    'George de Godzinsky',
    'George E. Lee',
    'George Greeley',
    'George Henschel',
    'George Olsen',
    'George SZELL',
    'George Vern Barnett',
    'Georges Prêtre',
    'Georges Sébastian',
    'Georges Tzipine',
    'Gérald Gagnier',
    'Gerard Schwarz',
    'Gerd Schaller',
    'Géza Anda',
    'Gian Piero Reverberi',
    'Giancarlo Chiaramello',
    'Giancarlo Guerrero',
    'Gil Dech',
    'Gilbert Varga',
    'Gintaras Rinkevičius',
    'Giorgio Federico Ghedini',
    'Gisele Ben-Dor',
    'Giulio Viozzi',
    'Giuseppe Antonicelli',
    'Giuseppe Bamboschek',
    'Giuseppe Martucci',
    'Giuseppe Patanè',
    'Giuseppe Sinopoli',
    'Godfrey Ridout',
    'Gonzalo Roig',
    'Gordon Cree',
    'Gordon Wry',
    'Grace Burrows',
    'Graeme Jenkins',
    'Graham George',
    'Grant Gershon',
    'Grant Llewellyn',
    'Gregory Batsleer',
    'Griffith Rhys Jones',
    'Grigori Gamburg',
    'Grigori Sandler',
    'Grzegorz Fitelberg',
    'Guido Cantelli',
    'Guido Santórsola',
    'Gundaris Pone',
    'Günter Bialas',
    'Günther Nierle',
    'Günther Ramin',
    'Gus Arnheim',
    'Gustav Ernesaks',
    'Gustav Kneip',
    'Gustav König',
    'Gustav Mahler',
    'Gustave Cloëz',
    'Gustavo DUDAMEL',
    'Guy Protheroe',
    'Guy Warrack',
    'H. Hugh Bancroft',
    'Hamilton Harty',
    'Hampartzoum Berberian',
    'Hans Carste',
    'Hans Felix Husadel',
    'Hans Gillesberger',
    'Hans Kindler',
    'Hans Richter-Haaser',
    'Hans Rosbaud',
    'Hans Schmidt-Isserstedt',
    'Hans Swarowsky',
    'Hans Wallat',
    'Hans-Hubert Schönzeler',
    'Harald Agersnap',
    'Harl McDonald',
    'Harold Blumenfeld',
    'Harold Byrns',
    'Harold Rosenbaum',
    'Harry Baisden',
    'Harry Bicket',
    'Harry Bidgood',
    'Harry Christophers',
    'Harry Horner Barnhart',
    'Harry Richman',
    'Hector Crawford',
    'Hector Gratton',
    'Heinrich Boell',
    'Heinrich Karl Strohm',
    'Heinz Bongartz',
    'Heinz Fricke',
    'Heinz Tietjen',
    'Heinz Unger',
    'Helen May Butler',
    'Henri Berger',
    'Henri Büsser',
    'Henri Pensis',
    'Henri René',
    'Henri Tomasi',
    'Henry Busse',
    'Henry Halstead',
    'Henry Kimball Hadley',
    'Henry Mancini',
    'Henry Mollicone',
    'Henry Schoenefeld',
    'Henry Sopkin',
    'Henry Swoboda',
    'Herbert Blomstedt',
    'Herbert Huffman',
    'Herbert L. Clarke',
    'Herbert Menges',
    'Herbert Schernus',
    'Herbert von KARAJAN',
    'Herman Fuchs',
    'Herman Strategier',
    'Hermann Scherchen',
    'Hermann Weigert',
    'Hermann Zilcher',
    'Hidemaro Konoye',
    'Hilary Davan Wetton',
    'Hilding Rosenberg',
    'Hiroshi Wakasugi',
    'Hobart Earle',
    'Hollis Dann',
    'Hong Nan-pa',
    'Horst Stein',
    'Horst-Tanu Margraf',
    'Houston Bright',
    'Howard Lanin',
    'Hryhoriy Veryovka',
    'Hryhory Kytasty',
    'Huang Yijun',
    'Hubert Klyne Headley',
    'Hugh Brunt',
    'Hugo Chaim Adler',
    'Hugo Distler',
    'Hugo Montenegro',
    'Hugo Reichenberger',
    'Hugo Riesenfeld',
    'Hugo Rignold',
    'Hyman Schandler',
    'Ichirō Fujiyama',
    'Ignace Strasfogel',
    'Igor Dronov',
    'Igor Markevitch',
    'Igor Stravinsky',
    'Imogen Holst',
    'Ioan Luchian Mihalea',
    'Ion Voicu',
    'Iona Brown',
    'Iris Lemare',
    'Irving Aaronson',
    'Irving Szathmary',
    'Irwin Hoffman',
    'Irwin Kostal',
    'Irwyn Ranald Walters',
    'Iša Krejčí',
    'Isham Jones',
    'Isidore Godfrey',
    'Iso Szajewicz',
    'Israel Yinon',
    'Issay Dobrowen',
    'Ivan Monighetti',
    'Ivan Romanoff',
    'Ivana Fišer',
    'Ivor Setterfield',
    'Izler Solomon',
    'J. Reilly Lewis',
    'Jaan Hargel',
    'Jaap Spaanderman',
    'Jaap van Zweden',
    'Jack Hylton',
    'Jack Westrup',
    'Jacob Avshalomov',
    'Jacqueline Fontyn',
    'Jacques Gershkovitch',
    'Jacques Singer',
    'Jaime Delgado Aparicio',
    'Jakov Gotovac',
    'James Adcock',
    'James Allen Gähres',
    'James Conlon',
    'James DePreist',
    'James Gayfer',
    'James Gourlay',
    'James Horner',
    'James Judd',
    'James Kempson',
    'James Lancelot',
    'James LEVINE',
    'James Loughran',
    'James MacMillan',
    'James Sample',
    'James Sherlock',
    'James William Webb-Jones',
    'Jan Garber',
    'Jan Latham-Koenig',
    'Jan Maklakiewicz',
    'Jan Meyerowitz',
    'Jan Savitt',
    'Jan Šoupal',
    'Jan Tausinger',
    'Jane Glover',
    'Jānis Kalniņš',
    'János Ferencsik',
    'János Fürst',
    'Jared DePasquale',
    'Jarmil Burghauser',
    'Jaroslav Řídký',
    'Jaroslav Vogel',
    'Jascha Horenstein',
    'Jascha Zayde',
    'Jay Kellner',
    'Jay Wilbur',
    'Jean Deslauriers',
    'Jean Goldkette',
    'Jean Martinon',
    'Jean Vallerand',
    'Jean-Marie Beaudet',
    'Jeannette Sorrell',
    'Jean-Pierre Jacquillat',
    'Jef van Hoof',
    'Jeff Alexander',
    'Jeff Wayne',
    'Jeffrey Kahane',
    'Jeffrey Skidmore',
    'Jeffrey Tate',
    'Jelly Roll Morton',
    'Jemal Gokieli',
    'Jenő Ádám',
    'Jeremy Summerly',
    'Jerry Bresler',
    'Jerzy Semkow',
    'Jessica Cottis',
    'Jésus Etcheverry',
    'Jesús López Cobos',
    'Jiří Bělohlávek',
    'Joana Carneiro',
    'JoAnn Falletta',
    'Joe Duddell',
    'Joe Sanders',
    'Johan Hye-Knudsen',
    'Johan Svendsen',
    'Johannes Brockt',
    'John Alldis',
    'John BARBIROLLI',
    'John Barry Talley',
    'John Carewe',
    'John Eliot GARDINER',
    'John Hollingsworth',
    'John Lanchbery',
    'John Landor',
    'John Mauceri',
    'John Ness Beck',
    'John Philip Sousa',
    'John Scott (composer)',
    'John Scott (organist)',
    'John Stepan Zamecnik',
    'John Williams',
    'Johnny Dunn',
    'Johnny Keating',
    'Johnny Wiggs',
    'Jón Leifs',
    'Jon Reed Sims',
    'Jonathan Sternberg',
    'Jonel Perlea',
    'Jordan Randall Smith',
    'Jorge Bolet',
    'Jorge Peixinho',
    'José Cubiles',
    'José Iturbi',
    'José Luis Rodríguez Vélez',
    'José Pablo Moncayo',
    'Josef Krips',
    'Josef Szulc',
    'Joseph Alfidi',
    'Joseph Colaneri',
    'Joseph Hawthorne',
    'Joseph Holbrooke',
    'Joseph Post',
    'Joseph Rescigno',
    'Joseph Rosenstock',
    'Joseph Silverstein',
    'Joseph Vandernoot',
    'Josephine Bradley',
    'Jože Privšek',
    'Jozef Cleber',
    'Juan Carlos Zorzi',
    'Juan José Castro',
    'Jules Gressier',
    'Jules Semler-Collery',
    'Julián Bautista',
    'Julián Carrillo',
    'Julian Pellicano',
    'Julian Perkins',
    'Julian Wachner',
    'Julien Ghyoros',
    'Julio Cueva',
    'Julio de Caro',
    'Julius Bürger',
    'Jussi Jalas',
    'Karel Ančerl',
    'Karel Kovařovic',
    'Karel Mark Chichon',
    'Karel Mengelberg',
    'Karel Šejna',
    'Karl BÖHM',
    'Karl Eliasberg',
    'Karl Elmendorff',
    'Karl King',
    'Karl Kritz',
    'Karl Maria Zwißler',
    'Karl Münchinger',
    'Karl Pilß',
    'Karl Rankl',
    'Karl Ristenpart',
    'Karl Zaruba',
    'Karol Stryja',
    'Kazuo Yamada',
    'Keith Bissell',
    'Keith Burstein',
    'Ken-Ichiro Kobayashi',
    'Kenneth Alwyn',
    'Kenneth Elloway',
    'Kenneth Kiesler',
    'Kenneth Montgomery',
    'Kenny Clayton',
    'Kid Thomas Valentine',
    'Kirill Kondrashin',
    'Klaudia Pasternak',
    'Klaus Fischer-Dieskau',
    'Klaus Martin Ziegler',
    'Klaus Tennstedt',
    'Knud Andersson',
    'Konstantin Listov',
    'Kosaku Yamada',
    'Kosta Manojlović',
    'Kostas Giannidis',
    'Krešimir Baranović',
    'Kristian Alexander',
    'Kristin Mellem',
    'Kunihiko Hashimoto',
    'Kurken Alemshah',
    'Kurt Herbert Adler',
    'Kurt Masur',
    'Kurt Overhoff',
    'Kurt Sanderling',
    'Kurt Wöss',
    'Ladislav Slovák',
    'Lajos Bárdos',
    'Lamar Stringfield',
    'Lamberto Gardelli',
    'Lamberto Landi',
    'László Lajtha',
    'László Weiner',
    'Lav Mirski',
    'Lehman Engel',
    'Leo Baxter',
    'Leo Borchard',
    'Leo F. Forbstein',
    'Leo Hussain',
    'Leo Reisman',
    'Leo Spies',
    'Léon Barzin',
    'León Zuckert',
    'Leonard BERNSTEIN',
    'Leonard Falcone',
    'Leonard Salzedo',
    'Leonard Slatkin',
    'Leopold STOKOWSKI',
    'Leslie Heward',
    'Leslie Woodgate',
    'Lew Douglas',
    'Lew Stone',
    'Lil Hardin Armstrong',
    'Linda Bouchard',
    'Linden Lundstrom',
    'Lionel Newman',
    'Loek Dikker',
    'Lola Castegnaro',
    'Lorenc Antoni',
    'Lorene Harrison',
    'Lorin Maazel',
    'Lorna Cooke deVaron',
    'Louis Applebaum',
    'Louis Beydts',
    'Louis Fourestier',
    'Louis Halsey',
    'Louis Lipstone',
    'Louis-Albert Bourgault-Ducoudray',
    'Lovro von Matačić',
    'Lucien Martin',
    'Lucijan Marija Škerjanc',
    'Lucio Agostini',
    'Lud Gluskin',
    'Ludolf Nielsen',
    'Luigi von Kunits',
    'Luis Gianneo',
    'Mabel Wheeler Daniels',
    'Madarash Oksana',
    'Magnar Mangersnes',
    'Magnus Loddgard',
    'Magnus Martensson',
    'Mal Hallett',
    'Malcolm Lockyer',
    'Malcolm Sargent',
    'Manno Wolf-Ferrari',
    'Manoah Leide-Tedesco',
    'Mansel Thomas',
    'Mantovani',
    'Marc Lavry',
    'Marcel Cariven',
    'Marcel Couraud',
    'Marcel Wengler',
    'Marcelle de Manziarly',
    'Margaret Hillis',
    'Marguerite Canal',
    'Marian Neuteich',
    'Marin Alsop',
    'Mario Rossi',
    'Mariss JANSONS',
    'Marius Constant',
    'Marius Stravinsky',
    'Mark Eager',
    'Mark Elder',
    'Mark Ermler',
    'Mark Lubbock',
    'Mark Stringer',
    'Marlon Daniel',
    'Martin Flämig',
    'Martin Isepp',
    'Martin Schlumpf',
    'Martin Yates',
    'Masaru Kawasaki',
    'Matthew Aucoin',
    'Matthias Pintscher',
    'Maurice Abravanel',
    'Maurice Goldman',
    'Maurice Handford',
    'Maurice Peress',
    'Maurice Zbriger',
    'Maurizio Benini',
    'Max Bruch',
    'Max Deutsch',
    'Max Goberman',
    'Max Leon',
    'Max Schönherr',
    'Maxwell Fernie',
    'Mei-Ann Chen',
    'Melville Cook',
    'Meredith Davies',
    'Merle Evans',
    'Meyer Lutz',
    'Michael Bialoguski',
    'Michael Bowles',
    'Michael Flagstad',
    'Michael Heming',
    'Michael Kamen',
    'Michael Kibblewhite',
    'Michael Maluntsian',
    'Michael Minsky',
    'Michael Nicholas',
    'Michael TILSON THOMAS',
    'Michael Tippett',
    'Mieczysław Karłowicz',
    'Miff Mole',
    'Mihail Jora',
    'Miklós Erdélyi',
    'Milan Munclinger',
    'Miloslav Kabeláč',
    'Milton Preves',
    'Milton Rosenstock',
    'Mirga Gražinytė-Tyla',
    'Miroslav Venhoda',
    'Mischa Bakaleinikoff',
    'Mitchell Ayres',
    'Mitja Nikisch',
    'Mogens Wöldike',
    'Montague Birch',
    'Mordechai Rechtman',
    'Morton Gould',
    'Mosco Carner',
    'Mstislav Rostropovich',
    'Muir Mathieson',
    'Murray Perahia',
    'Murry Sidlin',
    'Myer Fredman',
    'Myers Foggin',
    'Mykola Leontovych',
    'Myron Michailidis',
    'Nándor Zsolt',
    'Nathalie Stutzmann',
    'Neeme Järvi',
    'Neil Thomson',
    'Neko Saito',
    'Neville MARRINER',
    'Nicholas Carthy',
    'Nicholas Childs',
    'Nicholas Collon',
    'Nicholas Daniel',
    'Nicholas Kraemer',
    'Nicholas McGegan',
    'Nicola Rescigno',
    'Nicolas Achten',
    'Nikolai Anosov',
    'Nikolai Golovanov',
    'Nikolai Rakov',
    'Nikolaus HARNONCOURT',
    'Nils Grevillius',
    'Nimrod David Pfeffer',
    'Nino Marcelli',
    'Nino Sanzogno',
    'Norman Del Mar',
    'Norman Leyden',
    'Norman Luboff',
    'Norman O\'Neill',
    'Norman Scribner',
    'Norrie Paramor',
    'Ohannes Tchekidjian',
    'Okko Kamu',
    'Oksana Lyniv',
    'Olaf Kopvillem',
    'Olav Gurvin',
    'Olav Kielland',
    'Oleg Caetani',
    'Olive Smith',
    'Oliver Gilmour',
    'Oliver Knussen',
    'Oliviero De Fabritiis',
    'Omer Létourneau',
    'Onisim Bron',
    'Oscar Rabin',
    'Osman Zeki Üngör',
    'Oswald Cheesman',
    'Oswald Kabasta',
    'Otakar Jeremiáš',
    'Otmar Suitner',
    'Ottmar Gerster',
    'Otto Gerdes',
    'Otto KLEMPERER',
    'Owain Arwel Hughes',
    'P. R. Bidez',
    'Paavo Järvi',
    'Pablo Sorozábal',
    'Parviz Mahmoud',
    'Patrick Conway',
    'Paul Agnew',
    'Paul Ash',
    'Paul Ben-Haim',
    'Paul Bonneau',
    'Paul Breisach',
    'Paul Csonka',
    'Paul Hindemith',
    'Paul J. Christiansen',
    'Paul Kildea',
    'Paul Mauriat',
    'Paul McCreesh',
    'Paul Paviour',
    'Paul Pratt',
    'Paul Sacher',
    'Paul Specht',
    'Paul Steinitz',
    'Paul V. Yoder',
    'Paul van Kempen',
    'Paul Weston',
    'Paul Whiteman',
    'Pavel Feldt',
    'Pavel Klinichev',
    'Peggy Stuart Coolidge',
    'Percival Mackey',
    'Peter Bassano',
    'Peter Erős',
    'Peter G. Dyson',
    'Peter G. Fletcher',
    'Peter Herman Adler',
    'Peter Kreuder',
    'Peter Manning',
    'Peter Oundjian',
    'Peter Reulein',
    'Peter Ruzicka',
    'Peter Stanley Lyons',
    'Peter Tiboris',
    'Peter Wilhousky',
    'Phil Baxter',
    'Philip James',
    'Philip Mackenzie',
    'Philip Stopford',
    'Philipp Jarnach',
    'Philippe Auguin',
    'Pierre BOULEZ',
    'Pierre Hétu',
    'Pinchas Steinberg',
    'Pino Calvi',
    'Pino Presti',
    'Pippo Barzizza',
    'Primo Casale',
    'Rachel Zeffira',
    'Radamés Gnattali',
    'Rae Jenkins',
    'Rafael Frühbeck de Burgos',
    'Rafael KUBELÍK',
    'Rafael Payare',
    'Rafael Schächter',
    'Rainer Hersch',
    'Ralph Lyford',
    'Ralph Woodward',
    'Ramón Tebar',
    'Ray Heindorf',
    'Ray Sinatra',
    'Raymond Agoult',
    'Red Perkins',
    'Reg Owen',
    'Reginald Goodall',
    'Reginald Jacques',
    'Renato Cellini',
    'Renato Fasano',
    'René Gagnier',
    'René Leibowitz',
    'Rengim Gökmen',
    'Reynaldo Hahn',
    'Riccardo CHAILLY',
    'Riccardo MUTI',
    'Richard Burgin',
    'Richard Davy',
    'Richard Dufallo',
    'Richard Farnes',
    'Richard Hazard',
    'Richard Hey Lloyd',
    'Richard Hickox',
    'Richard Hol',
    'Richard Laugs',
    'Richard M. Jones',
    'Richard P. Condie',
    'Richard Seal',
    'Richard Strauss',
    'Richard Westenburg',
    'Richard Woitach',
    'Richie Rome',
    'Ricky Hyslop',
    'Rio Gebhardt',
    'Robert Armbruster',
    'Robert Bernat',
    'Robert Farnon',
    'Robert Hart Baker',
    'Robert Huw Morgan',
    'Robert Prizeman',
    'Robert Spano',
    'Robert Still',
    'Robert Tear',
    'Robert Wysome',
    'Roberto Benzi',
    'Roberto Goitre',
    'Robin Ticciati',
    'Rodolfo Ferrari',
    'Rodrigo Prats',
    'Roger Désormière',
    'Roger Norrington',
    'Roger Wagner',
    'Rogier van Otterloo',
    'Rolf Agop',
    'Ross Pople',
    'Rossen Milanov',
    'Roy Newsome',
    'Royalton Kisch',
    'Rudolf Kempe',
    'Rudolf Moralt',
    'Rudolf Wagner-Régeny',
    'Rudolf Werthen',
    'Rudolph Dunbar',
    'Ruhollah Khaleqi',
    'Rupert D\'Cruze',
    'Russell Keable',
    'Ruth Gipps',
    'Said Rustamov',
    'Salvatore Dell\'Isola',
    'Sam Lanin',
    'Sam Pottle',
    'Sam Wooding',
    'Samuel Kaylin',
    'Sandor Harmati',
    'Sándor Jemnitz',
    'Sándor Végh',
    'Sarah Caldwell',
    'Sarah Ioannides',
    'Sarah Travis',
    'Scott Ellaway',
    'Seiji Ozawa',
    'Seóirse Bodley',
    'Serge Jaroff',
    'Serge Koussevitzky',
    'Sergei Rachmaninoff',
    'Sergiu CELIBIDACHE',
    'Sidney Torch',
    'Siegmund von Hausegger',
    'Silvestre Revueltas',
    'Silvio Barbato',
    'Sim Gokkes',
    'Šimon Jurovský',
    'Simon Over',
    'Simon Preston',
    'Simon Pullman',
    'Simon RATTLE',
    'Simon Streatfeild',
    'Sioned James',
    'Sonny Clay',
    'Speranza Scappucci',
    'Spiros Argiris',
    'Stanford Robinson',
    'Stanislav Gorkovenko',
    'Stanisław Skrowaczewski',
    'Stanisław Wisłocki',
    'Stanley Lebowsky',
    'Stanley Saunders',
    'Stefan Sanderling',
    'Stephen Cleobury',
    'Stephen Layton',
    'Steuart Bedford',
    'Steve Willaert',
    'Steven Kronauer',
    'Stewart Robertson',
    'Stig Westerberg',
    'Stuart Challender',
    'Susanna Mälkki',
    'Suzi Digby',
    'Sylvan Levin',
    'Szymon Goldberg',
    'Szymon Kataszek',
    'T. C. Kelly',
    'Tadaaki Otaka',
    'Tal Henry',
    'Tamara Brooks',
    'Tauno Hannikainen',
    'Tecwyn Evans',
    'Ted Lewis (musician)',
    'Teddy Abrams',
    'Teddy Petersen',
    'Terence Vaughan',
    'Theo Mackeben',
    'Theodore Bloomfield',
    'Theodore Carpenter',
    'Theodore Kuchar',
    'Thom de Klerk',
    'Thomas BEECHAM',
    'Thomas Fey',
    'Thomas Fulton',
    'Thomas Helmore',
    'Thomas Jensen',
    'Thomas Sanderling',
    'Thomas Schippers',
    'Thomas Sleeper',
    'Thomas Søndergård',
    'Thomas Wingham',
    'Thor Johnson',
    'Thurston Dart',
    'Tibor Harsányi',
    'Tibor Kozma',
    'Tibor Paul',
    'Timothy Rhea',
    'Todor Skalovski',
    'Tofig Guliyev',
    'Toivo Haapanen',
    'Tokichi Setoguchi',
    'Toni Ortelli',
    'Tor Aulin',
    'Tor Mann',
    'Trevor PINNOCK',
    'Tristram Cary',
    'Tsegmidiin Namsraijav',
    'Tullio Serafin',
    'Tyzen Hsiao',
    'Uberto Zanolli',
    'Ulf Björlin',
    'User talk:Musictogetherinfo',
    'Václav Dobiáš',
    'Václav Kašlík',
    'Václav Suk',
    'Valdemar Eiberg',
    'Valéria Csányi',
    'Valery Gergiev',
    'Vassili Nebolsin',
    'Vernon Elliott',
    'Victor Alessandro',
    'Victor Aloysius Meyers',
    'Victor Borge',
    'Victor de Sabata',
    'Victor Herbert',
    'Victor Paranjoti',
    'Victor Tevah',
    'Victor Urbancic',
    'Victoria Bond',
    'Viktor Ullmann',
    'Vincent Lopez',
    'Vítězslava Kaprálová',
    'Vittorio Monti',
    'Vivian Dunn',
    'Vladimir Altschuler',
    'Vladimir Ashkenazy',
    'Vladimir Golschmann',
    'Vladimir Ponkin',
    'Vladimir Ziva',
    'Volodymyr Runchak',
    'Waldo de los Ríos',
    'Wallace Arthur Sabin',
    'Walter B. Hargreaves',
    'Walter MacNutt',
    'Walter Susskind',
    'Walter V. Bozyk',
    'Walter Weller',
    'Warwick Braithwaite',
    'Werner Eisbrenner',
    'Werner Janssen',
    'Werner Torkanowsky',
    'Wieland Kuijken',
    'Wilfrid Pelletier',
    'Wilhelm FURTWÄNGLER',
    'Wilhelm Georg Berger',
    'Wilhelm Grosz',
    'Wilhelm Neef',
    'Wilhelm Schüchter',
    'Wilhelm Stenhammar',
    'Will Crutchfield',
    'Willard Robison',
    'Willem van Otterloo',
    'Willi Boskovsky',
    'William Alwyn',
    'William C. K. Irwin',
    'William Grant Still',
    'William Ifor Jones',
    'William Lacey',
    'William Loose',
    'William Merrigan Daly',
    'William Steinberg',
    'Willy Berking',
    'Wilmer Watts',
    'Władysław Raczkowski',
    'Wolf Gorelik',
    'Wolfgang Fortner',
    'Wolfgang Sawallisch',
    'Wolfgang Stresemann',
    'Wyn Morris',
    'Xian Zhang',
    'Yakov Kreizberg',
    'Yannick Nézet-Séguin',
    'Yevgeny MRAVINSKY',
    'Yoko Kanno',
    'Yoshio Shigezono',
    'Yuri Fayer',
    'Yuri Temirkanov',
    'Yuzo Toyama',
    'Zbyněk Vostřák',
    'Zdeněk Chalabala',
    'Zef Çoba',
    'Zoltán Rozsnyai',
    'Zubin MEHTA',
    'Zygmunt Białostocki'
    ]